//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratedModels {
    using System;
    
    
    public class TestModelClass {
        
        // The width of the object.
        private double widthValue;
        
        // The Width property for the object.
        public double Width {
            get {
                return this.widthValue;
            }
        }
    }
}
